import { Movie } from "./types";

export const MOCK_MOVIES: Movie[] = [
  {
    id: "1",
    type: "movie",
    title: "The Midnight Horizon",
    description: "In a world where the sun never rises, a lone explorer discovers a secret that could bring back the light, but at a cost that might be too high for humanity to pay.",
    thumbnail: "https://picsum.photos/seed/horizon/400/600",
    backdrop: "https://picsum.photos/seed/horizon-bg/1920/1080",
    rating: 8.4,
    year: 2024,
    duration: "2h 15m",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    isTrending: true,
  },
  {
    id: "2",
    type: "movie",
    title: "Neon Shadows",
    description: "A cybernetic detective in a rain-soaked metropolis hunts down a rogue AI that has started to develop human emotions and a thirst for vengeance.",
    thumbnail: "https://picsum.photos/seed/neon/400/600",
    backdrop: "https://picsum.photos/seed/neon-bg/1920/1080",
    rating: 7.9,
    year: 2023,
    duration: "1h 58m",
    genre: ["Action", "Cyberpunk", "Thriller"],
    isTrending: true,
  },
  {
    id: "3",
    type: "movie",
    title: "Whispers of the Forest",
    description: "An ancient forest holds secrets that have been forgotten for millennia. When a young girl wanders too deep, she finds herself at the center of a battle between nature and progress.",
    thumbnail: "https://picsum.photos/seed/forest/400/600",
    backdrop: "https://picsum.photos/seed/forest-bg/1920/1080",
    rating: 8.1,
    year: 2024,
    duration: "1h 45m",
    genre: ["Fantasy", "Family"],
    isNew: true,
  },
  {
    id: "4",
    type: "movie",
    title: "The Last Alchemist",
    description: "In an alternate 19th century, alchemy is the dominant science. One man must find the philosopher's stone to save his dying kingdom from an unstoppable plague.",
    thumbnail: "https://picsum.photos/seed/alchemist/400/600",
    backdrop: "https://picsum.photos/seed/alchemist-bg/1920/1080",
    rating: 8.7,
    year: 2024,
    duration: "2h 30m",
    genre: ["History", "Fantasy", "Mystery"],
    isTrending: true,
  },
  {
    id: "5",
    type: "movie",
    title: "Velocity Peak",
    description: "High-stakes mountain racing reaches new heights as a group of adrenaline junkies compete in the most dangerous race ever conceived by man.",
    thumbnail: "https://picsum.photos/seed/peak/400/600",
    backdrop: "https://picsum.photos/seed/peak-bg/1920/1080",
    rating: 6.8,
    year: 2023,
    duration: "1h 32m",
    genre: ["Action", "Sport"],
  },
  {
    id: "6",
    type: "movie",
    title: "Echoes of Silence",
    description: "A musician who lost her hearing must find a new way to connect with the world and her art, leading her on a journey of self-discovery across Europe.",
    thumbnail: "https://picsum.photos/seed/echoes/400/600",
    backdrop: "https://picsum.photos/seed/echoes-bg/1920/1080",
    rating: 8.9,
    year: 2024,
    duration: "2h 05m",
    genre: ["Drama", "Music"],
    isNew: true,
  },
  {
    id: "7",
    type: "movie",
    title: "Quantum Paradox",
    description: "Time travel is real, but it's not what we expected. Every jump creates a new reality, and one man is trying to find his way back to the original timeline.",
    thumbnail: "https://picsum.photos/seed/quantum/400/600",
    backdrop: "https://picsum.photos/seed/quantum-bg/1920/1080",
    rating: 7.5,
    year: 2023,
    duration: "2h 10m",
    genre: ["Sci-Fi", "Thriller"],
  },
  {
    id: "8",
    type: "movie",
    title: "The Great Heist",
    description: "A team of specialized thieves plans the ultimate robbery: stealing the crown jewels during a live global broadcast.",
    thumbnail: "https://picsum.photos/seed/heist/400/600",
    backdrop: "https://picsum.photos/seed/heist-bg/1920/1080",
    rating: 8.2,
    year: 2024,
    duration: "1h 55m",
    genre: ["Crime", "Action"],
    isTrending: true,
  }
];
